// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIdroChtYxw1qI3kSA6aeZc40x1_ezIcU',
    appId: '1:880257631582:web:6c8da3952a35581364bbcf',
    messagingSenderId: '880257631582',
    projectId: 'gida-service',
    authDomain: 'gida-service.firebaseapp.com',
    storageBucket: 'gida-service.firebasestorage.app',
    measurementId: 'G-ENJ5B96B38',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGRJqHvZIlz8Gp1wFPXql9bYUvC8ZFUXo',
    appId: '1:880257631582:android:f71e14db2f060cb964bbcf',
    messagingSenderId: '880257631582',
    projectId: 'gida-service',
    storageBucket: 'gida-service.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA35ZtKcd3iiWvgkzQSaS6ID0DQp_lY7sU',
    appId: '1:880257631582:ios:49005a3668383cce64bbcf',
    messagingSenderId: '880257631582',
    projectId: 'gida-service',
    storageBucket: 'gida-service.firebasestorage.app',
    iosClientId:
        '880257631582-3k7hj6mg62g2kus4ttaavpapnhjcvajg.apps.googleusercontent.com',
    iosBundleId: 'com.example.gidaServices',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA35ZtKcd3iiWvgkzQSaS6ID0DQp_lY7sU',
    appId: '1:880257631582:ios:49005a3668383cce64bbcf',
    messagingSenderId: '880257631582',
    projectId: 'gida-service',
    storageBucket: 'gida-service.firebasestorage.app',
    iosClientId:
        '880257631582-3k7hj6mg62g2kus4ttaavpapnhjcvajg.apps.googleusercontent.com',
    iosBundleId: 'com.example.gidaServices',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIdroChtYxw1qI3kSA6aeZc40x1_ezIcU',
    appId: '1:880257631582:web:ce99a6b5a47df25a64bbcf',
    messagingSenderId: '880257631582',
    projectId: 'gida-service',
    authDomain: 'gida-service.firebaseapp.com',
    storageBucket: 'gida-service.firebasestorage.app',
    measurementId: 'G-ZNL8L0FJ6F',
  );
}
